# wrangler.toml

# 這是您在 Cloudflare 上的 Pages 專案名稱
# 請記得將 "stockbacktest-deploy" 換成您在步驟一中建立的最新專案名稱
name = "stockbacktest-deploy"

# 這是將 R2 儲存貯體「繫結」到您 Worker 的設定
[[r2_buckets]]
binding = "STOCK_DATA_BUCKET"
bucket_name = "stockbacktest-data"

# [新增] 這是告訴 Wrangler 我們 Pages 專案的結構
[pages_build_output]
# 靜態檔案的目錄
dir = "public"
# Pages Functions 的根目錄
functions-root = "functions"
