name: Deploy to Cloudflare

on:
  # 當有程式碼推送到 main 分支時觸發
  push:
    branches:
      - main
  
  # 允許在 GitHub Actions 頁面手動觸發此工作流
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # 移除 cache: 'npm' 選項，因為專案中缺少 package-lock.json 檔案
          # 最佳實踐是執行 npm install 並將產生的 package-lock.json 提交到您的儲存庫中，然後再重新啟用此快取功能。
      
      - name: Install dependencies
        run: npm install

      - name: Deploy to Cloudflare Pages
        env:
          # CLOUDFLARE_API_TOKEN 和 CLOUDFLARE_ACCOUNT_ID 需設定在 GitHub > Settings > Secrets and variables > Actions
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          # 執行我們在 package.json 中定義的部署指令
          npm run deploy
